---
# tasks file for playbooks/roles/wordpress
- name: "wp- update cache"
  apt:
    update_cache: yes
  become: yes

- name: install packages
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_name }}"

- name: Install the MySQL
  become: yes
  pip:
    name: "{{ item }}"
    state: forcereinstall
  with_items:
    - pip
    - MySQL-python

- name: "start apache2 mysql"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - apache2
    - mysql

- name: "install php packages"
  apt:
    name: "php,php-mysql,php-xml,php-mbstring,php-mcrypt,php-gd,php-intl"
    state: "present"
  # force boolean evaluation
  when: php_install|bool
  # We need to startapache
- name: "apache service activation"
  service: 
    name: "apache2"
    state: "restarted"
