---
- name: "install db"
  become: yes
  mysql_db:
    name: "{{ mysql_db }}"

- name: "Create user"
  mysql_user: 
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
  become: yes

