---
# tasks file for playbooks/roles/wordpress
- name: "wp- update cache"
  apt:
    update_cache: yes
  become: yes

- name: install word
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_name }}"

- name: "start apache2 mysql"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - apache2
    - mysql

